name: Monitor Docker Tag and Rename Folder

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - napcat  # 触发工作流的分支

jobs:
  update-folder:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Docker tag
        id: get_docker_tag
        run: |
          tag=$(curl -s "https://hub.docker.com/v2/repositories/mlikiowa/napcat-docker/tags/?page_size=100" | jq -r '.results[1].name' | awk '{sub(/^v/, ""); print}')
          echo "Docker tag: $tag"
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Get current folder name
        id: get_current_folder
        run: |
          folder_name=$(ls napcat | head -n 1)
          echo "Current folder name: $folder_name"
          echo "current_folder_name=$folder_name" >> $GITHUB_ENV

      - name: Compare and update folder name
        if: ${{ env.current_folder_name != env.tag }}
        run: |
          echo "Folder needs to be updated."
          mv "napcat/${{ env.current_folder_name }}" "napcat/${{ env.tag }}"
          git add napcat
          git commit -m "Update folder name to ${TAG}"
          git push origin napcat

      - name: Notify if no update needed
        if: ${{ env.current_folder_name == env.tag }}
        run: echo "No folder update needed. Current folder name is already ${TAG}"
