name: Monitor Docker Tag and Rename Folder

on:
  schedule:
    - cron:  '52 * * * *'
  workflow_dispatch:

jobs:
  update-folder:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: napcat

      - name: Get Docker tag
        id: get_docker_tag
        run: |
          tag=$(curl -s "https://hub.docker.com/v2/repositories/mlikiowa/napcat-docker/tags/?page_size=100" | jq -r '.results[1].name' | awk '{sub(/^v/, ""); print}')
          echo "Docker tag: $tag"
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Check current directory contents
        run: |
          echo "Current directory contents:"
          ls -la /home/runner/work/napcat-1panel/napcat-1panel

      - name: Get current folder name
        id: get_current_folder
        run: |
          current_folder=$(ls /home/runner/work/napcat-1panel/napcat-1panel | head -n 1)
          echo "Current folder name: $current_folder"
          echo "current_folder_name=$current_folder" >> $GITHUB_ENV

      - name: Compare and rename folder
        if: ${{ env.current_folder_name != env.tag }}
        run: |
          current_folder="/home/runner/work/napcat-1panel/napcat-1panel/${{ env.current_folder_name }}"
          target_folder="/home/runner/work/napcat-1panel/napcat-1panel/${{ env.tag }}"
          
          echo "Current folder path: $current_folder"
          echo "Target folder path: $target_folder"

          if [ -d "$current_folder" ]; then
            echo "Renaming folder."
            mv "$current_folder" "$target_folder"
            git config --global user.email "920113370213@njust.edu.cn"
            git config --global user.name "Fahaxikiiii"
            git add .
            git commit -m "Rename folder from ${current_folder_name} to ${TAG}"
            git push origin napcat
          else
            echo "Source folder '$current_folder' does not exist."
            exit 1
          fi

      - name: Notify if no rename needed
        if: ${{ env.current_folder_name == env.tag }}
        run: echo "No folder rename needed. Current folder name is already ${TAG}"
